device {
    name = uniw0001-00-093a:0255-touchpad
    sensitivity = -1
}
device {
    name = uniw0001-00-093a:0255-mouse
    sensitivity = -1
}
device {
    name = logitech-g305-1
    sensitivity = -.3
}